In [2]:
from PIL import Image
import numpy as np

In [3]:
path = r'C:\Users\R\PycharmProjects\Thesis_cur-AI-tor\images\ff742b8e8e6120f27ec567f60143fc82.jpg'

img = Image.open(path)
red_channel = np.array(img.getchannel(0))
# img.shape

In [4]:
# red_channel_array = np.array(red_channel)

width = red_channel.shape[0]
height = red_channel.shape[1]

print(f'h, w: {height}, {width}')

h, w: 400, 371


In [5]:
l = []

def divide_img_blocks(img, n_blocks=(3, 3)):
    horizontal = np.array_split(img, n_blocks[0])
    split_img = [np.array_split(block, n_blocks[1], axis=1) for block in horizontal]
    return np.asarray(split_img, dtype=np.ndarray).reshape(n_blocks)

result = divide_img_blocks(red_channel)

for i in range(result.shape[0]):
    for j in range(result.shape[1]):
        l.append(result[i,j])

ValueError: cannot reshape array of size 148400 into shape (1,1)

In [34]:
result.shape

(3, 3)

In [39]:
result[0][0].shape

(124, 134)

In [40]:
result[1][0].shape

(124, 134)

In [41]:
result[2][0].shape


(123, 134)

In [42]:
result[2][0]


array([[145, 132, 207, ..., 210, 223, 230],
       [126, 135, 194, ..., 207, 218, 232],
       [118, 126, 165, ..., 207, 211, 228],
       ...,
       [100, 135, 167, ..., 213, 208, 227],
       [ 92, 165, 205, ..., 217, 210, 225],
       [ 93, 177, 218, ..., 221, 212, 223]], dtype=uint8)

In [46]:
im = Image.fromarray(result[0][0])
im.show()

In [47]:
l

[array([[100, 100, 104, ...,  38,  38,  20],
        [102, 106, 112, ...,  24,  31,  18],
        [105, 107, 112, ...,  18,  27,  26],
        ...,
        [203, 174, 148, ...,  97, 126,  35],
        [176, 190, 200, ...,  57, 122,  35],
        [153, 188, 224, ...,  58, 136,  67]], dtype=uint8),
 array([[ 18,  21,  19, ...,   7,  10,  13],
        [ 11,   2,  14, ...,  27,  19,  16],
        [ 20,   6,  12, ...,  32,  32,  39],
        ...,
        [ 77,  58,  83, ..., 131,  33,  69],
        [ 71,  73,  88, ...,  70,   7,  40],
        [ 70,  73,  59, ...,  47,  74,  61]], dtype=uint8),
 array([[ 13,  10,  13, ..., 126, 127, 127],
        [ 17,  13,  14, ..., 121, 124, 123],
        [ 42,  35,  32, ..., 121, 124, 121],
        ...,
        [ 73,  85,  58, ..., 116, 116, 120],
        [ 61,  38,  43, ..., 113, 115, 118],
        [ 63,  45,  60, ..., 113, 115, 118]], dtype=uint8),
 array([[134, 192, 209, ...,  48, 108,  85],
        [140, 211, 194, ...,  76, 113, 130],
        [123, 13